<script setup lang="ts">
useHead({
  title: "Create Turborepo (vue-nuxt:docs)",
  meta: [{ name: "description", content: "Generated by create turbo" }],
});
const email = ref("");
const password = ref("");

const isLoading = ref(false);
async function onSubmit(event: Event) {
  event.preventDefault();
  isLoading.value = true;

  setTimeout(() => {
    isLoading.value = false;
  }, 3000);
}
</script>

<template>
  <NuxtLayout>
    <div class="flex justify-center items-center h-screen">
      <form class="flex gap-2 flex-col w-96" @submit="onSubmit">
        <div class="flex flex-col space-y-2 text-center">
          <h1 class="text-2xl font-semibold tracking-tight">Nuxt + Turbo</h1>
          <p class="text-sm text-muted-foreground">
            Enter your email below to login in your account
          </p>
        </div>
        <UiLabel for="email">Email</UiLabel>
        <UiInput id="email" v-model="email" type="email" />
        <UiLabel for="password">Password</UiLabel>
        <UiInput id="password" v-model="password" type="password" />
        <UiButton> Login </UiButton>
      </form>
    </div>
  </NuxtLayout>
</template>
